@api = http://localhost:5000/api/tasks

###
GET {{api}}
###
GET {{api}}/1
###
POST {{api}}
Content-Type: application/json

{
    "title": "Task two",
    "description": "Description two"
}
###
PUT {{api}}/1
Content-Type: application/json

{
    "title": "Task one",
    "description": "Description one"
}
###
DELETE {{api}}/1